### PR TITLE
fix nip27 test

### PR DESCRIPTION
**Pull request by zappityzap**
This fixes the failing nip27 test. I have no idea why. Typescript hurts my brain.

### CODE REVIEW

**Comment by alexgleason** [comment]
Does this test actually fail? Changing it back defeats the purpose... maybe TypeScript in the CI needs to be updated. I didn't realize I had merged a failing test.

**Comment by zappityzap** [comment]
The test fails since #241. I don't know if this is the right fix, but the test passes.

The nip05 test has been failing for a while and obscuring other failed tests. nip05 test is failing because the channel.ninja is gone: https://github.com/channelninja/channel.ninja

Summary of all failing tests
 FAIL  ./nip27.test.ts
  ● Test suite failed to run

    nip27.ts:63:7 - error TS2322: Type 'DecodeValue<"nprofile" | "nrelay" | "nevent" | "naddr" | "nsec" | "npub" | "note">' is not assignable to type 'DecodeResult'.
      Type 'DecodeValue<"nprofile" | "nrelay" | "nevent" | "naddr" | "nsec" | "npub" | "note">' is not assignable to type 'DecodeValue<"nprofile">'.
        Type '"nprofile" | "nrelay" | "nevent" | "naddr" | "nsec" | "npub" | "note"' is not assignable to type '"nprofile"'.
          Type '"nrelay"' is not assignable to type '"nprofile"'.

    63       decoded: decode(value)
             ~~~~~~~

      nip21.ts:21:3
        21   decoded: DecodeResult
             ~~~~~~~
        The expected type comes from property 'decoded' which is declared here on type 'NostrURI'

**Comment by alexgleason** [comment]
This is the fix here: https://github.com/nbd-wtf/nostr-tools/pull/249

Thanks for raising the issue!
